### ISSUE TITLE
Is this module support 64bit architecture ?

### ISSUE THREAD

**Issue by ydeshayes** [acktie/Acktie-Mobile-iOS-QR-Reader#2]
http://www.appcelerator.com/blog/2015/01/titanium-sdk-3-5-0-ga-now-available-with-64-bit-ios-support/

With the 3.5.0 update all iOS modules will need to be 64-bit compatible.

Can't you do something for this ?

**Comment by TNuzzi** [comment]
Added 2.2, it is built for 64-bit support.

**Comment by milgner** [comment]
Looks like `libzbar.a` also needs recompilation as it's still missing 64-bit symbols.

**Comment by TNuzzi** [comment]
Fixed.  Added 2.3.  libzbar is 64 bit now.

**Comment by milgner** [comment]
Fantastic! Thanks for the quick update, works great now! :+1:
