### ISSUE TITLE
xcode version

### ISSUE THREAD

**Issue by pixelstudioro** [acktie/Acktie-Mobile-iOS-QR-Reader#5]
what xcode version you used?
when i try to compile the code, it's create the module and when i want to use it i get:

[ERROR] :  *\* BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/test.build/Debug-iphonesimulator/test-universal.build/Objects-normal/i386/test normal i386
[ERROR] :   Ld build/test.build/Debug-iphonesimulator/test-universal.build/Objects-normal/x86_64/test normal x86_64
[ERROR] :  (2 failures)

if i get the compiled version from gittio everything is ok, when i try to compile with python doesn't work

**Comment by TNuzzi** [comment]
I am using the latest version 6.1.1.  I also have a convenient script called appBuild.sh that I use to rebuild the module.

**Comment by pixelstudioro** [comment]
Yes. appBuild.sh fixed that error. Thanks.
